<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // ==========================================
            // 1. SAINS & DEVELOPER
            // ==========================================
            [
                'category_id' => 1,
                'title' => 'Clean Code',
                'slug' => 'clean-code',
                'author' => 'Robert C. Martin',
                'price' => 450000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 1200,
                'cover' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=500',
                'description' => 'Panduan menulis kode yang rapi dan profesional.',
            ],
            [
                'category_id' => 1,
                'title' => 'Refactoring',
                'slug' => 'refactoring',
                'author' => 'Martin Fowler',
                'price' => 520000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 3,
                'sold_count' => 850,
                'cover' => 'https://images.unsplash.com/photo-1532012197367-2d5970d7758d?q=80&w=500',
                'description' => 'Teknik memperbaiki desain kode yang sudah ada.',
            ],
            [
                'category_id' => 1,
                'title' => 'The Pragmatic Programmer',
                'slug' => 'the-pragmatic-programmer',
                'author' => 'Andrew Hunt',
                'price' => 480000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 10,
                'sold_count' => 2100,
                'cover' => 'https://images.unsplash.com/photo-1589998059171-988d887df646?q=80&w=500',
                'description' => 'Perjalanan menjadi master programmer sejati.',
            ],
            [
                'category_id' => 1,
                'title' => 'Design Patterns',
                'slug' => 'design-patterns',
                'author' => 'Erich Gamma',
                'price' => 600000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 5,
                'sold_count' => 450,
                'cover' => 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?q=80&w=500',
                'description' => 'Solusi reusable untuk masalah software umum.',
            ],
            [
                'category_id' => 1,
                'title' => 'Introduction to Algorithms',
                'slug' => 'intro-to-algorithms',
                'author' => 'Thomas H. Cormen',
                'price' => 850000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 12,
                'sold_count' => 300,
                'cover' => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=500',
                'description' => 'Buku wajib untuk memahami struktur data.',
            ],

            // ==========================================
            // 2. KEDOKTERAN
            // ==========================================
            [
                'category_id' => 2,
                'title' => 'Anatomi Tubuh Dasar',
                'slug' => 'anatomi-tubuh-dasar',
                'author' => 'Henry Gray',
                'price' => 350000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 1500,
                'cover' => 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=500',
                'description' => 'Panduan lengkap anatomi tubuh manusia.',
            ],
            [
                'category_id' => 2,
                'title' => 'Prinsip Bedah Modern',
                'slug' => 'prinsip-bedah-modern',
                'author' => 'Schwartz',
                'price' => 650000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 5,
                'sold_count' => 420,
                'cover' => 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=500',
                'description' => 'Dasar-dasar teknik bedah klinis terbaru.',
            ],
            [
                'category_id' => 2,
                'title' => 'Farmakologi Dasar',
                'slug' => 'farmakologi-dasar',
                'author' => 'Katzung',
                'price' => 420000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 8,
                'sold_count' => 980,
                'cover' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=500',
                'description' => 'Mekanisme kerja obat pada tubuh.',
            ],
            [
                'category_id' => 2,
                'title' => 'Harrisons Internal Medicine',
                'slug' => 'harrisons-internal-medicine',
                'author' => 'Tinsley Harrison',
                'price' => 1200000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 2,
                'sold_count' => 150,
                'cover' => 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=500',
                'description' => 'Referensi utama ilmu penyakit dalam.',
            ],
            [
                'category_id' => 2,
                'title' => 'Atlas of Human Anatomy',
                'slug' => 'atlas-of-human-anatomy',
                'author' => 'Frank H. Netter',
                'price' => 950000,
                'discount_percentage' => 20,
                'is_on_sale' => true,
                'stock' => 7,
                'sold_count' => 600,
                'cover' => 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?q=80&w=500',
                'description' => 'Ilustrasi anatomi medis paling populer.',
            ],

            // ==========================================
            // 3. EKONOMI & BISNIS
            // ==========================================
            [
                'category_id' => 3,
                'title' => 'Rich Dad Poor Dad',
                'slug' => 'rich-dad-poor-dad',
                'author' => 'Robert Kiyosaki',
                'price' => 125000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 20,
                'sold_count' => 5400,
                'cover' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=500',
                'description' => 'Mengubah mindset tentang uang dan aset.',
            ],
            [
                'category_id' => 3,
                'title' => 'The Lean Startup',
                'slug' => 'the-lean-startup',
                'author' => 'Eric Ries',
                'price' => 180000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 8,
                'sold_count' => 3200,
                'cover' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=500',
                'description' => 'Membangun bisnis dengan metodologi efisien.',
            ],
            [
                'category_id' => 3,
                'title' => 'Zero to One',
                'slug' => 'zero-to-one',
                'author' => 'Peter Thiel',
                'price' => 160000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 4100,
                'cover' => 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?q=80&w=500',
                'description' => 'Membangun startup yang menciptakan masa depan.',
            ],
            [
                'category_id' => 3,
                'title' => 'The Intelligent Investor',
                'slug' => 'the-intelligent-investor',
                'author' => 'Benjamin Graham',
                'price' => 250000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 10,
                'sold_count' => 2900,
                'cover' => 'https://images.unsplash.com/photo-1611974717483-586733c375d0?q=80&w=500',
                'description' => 'Alkitab bagi para investor saham dunia.',
            ],
            [
                'category_id' => 3,
                'title' => 'Blue Ocean Strategy',
                'slug' => 'blue-ocean-strategy',
                'author' => 'W. Chan Kim',
                'price' => 220000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 1800,
                'cover' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=500',
                'description' => 'Menciptakan pasar baru tanpa kompetisi.',
            ],

            // ==========================================
            // 4. SASTRA & SENI
            // ==========================================
            [
                'category_id' => 4,
                'title' => 'Sapiens',
                'slug' => 'sapiens',
                'author' => 'Yuval Noah Harari',
                'price' => 200000,
                'discount_percentage' => 20,
                'is_on_sale' => true,
                'stock' => 25,
                'sold_count' => 6700,
                'cover' => 'https://images.unsplash.com/photo-1543003919-a99570044ed0?q=80&w=500',
                'description' => 'Riwayat singkat umat manusia dari dulu.',
            ],
            [
                'category_id' => 4,
                'title' => 'Laskar Pelangi',
                'slug' => 'laskar-pelangi',
                'author' => 'Andrea Hirata',
                'price' => 95000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 30,
                'sold_count' => 10000,
                'cover' => 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?q=80&w=500',
                'description' => 'Kisah perjuangan anak-anak Belitung.',
            ],
            [
                'category_id' => 4,
                'title' => 'Bumi Manusia',
                'slug' => 'bumi-manusia',
                'author' => 'Pramoedya Ananta Toer',
                'price' => 145000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 20,
                'sold_count' => 8500,
                'cover' => 'https://images.unsplash.com/photo-1474932430478-3a7fb9083db0?q=80&w=500',
                'description' => 'Roman legendaris sejarah Indonesia.',
            ],
            [
                'category_id' => 4,
                'title' => 'The Art of War',
                'slug' => 'the-art-of-war',
                'author' => 'Sun Tzu',
                'price' => 85000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 40,
                'sold_count' => 15000,
                'cover' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=500',
                'description' => 'Filosofi perang dan strategi kepemimpinan.',
            ],
            [
                'category_id' => 4,
                'title' => 'Cantik Itu Luka',
                'slug' => 'cantik-itu-luka',
                'author' => 'Eka Kurniawan',
                'price' => 120000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 15,
                'sold_count' => 4500,
                'cover' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=500',
                'description' => 'Novel realisme magis Indonesia modern.',
            ],

            // ==========================================
            // 5. TEKNOLOGI AI
            // ==========================================
            [
                'category_id' => 5,
                'title' => 'Deep Learning',
                'slug' => 'deep-learning',
                'author' => 'Ian Goodfellow',
                'price' => 950000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 6,
                'sold_count' => 400,
                'cover' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=500',
                'description' => 'Dasar matematika dan algoritma deep learning.',
            ],
            [
                'category_id' => 5,
                'title' => 'Hands-On Machine Learning',
                'slug' => 'hands-on-machine-learning',
                'author' => 'Aurélien Géron',
                'price' => 780000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 9,
                'sold_count' => 1100,
                'cover' => 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?q=80&w=500',
                'description' => 'Implementasi ML dengan Scikit-Learn dan TensorFlow.',
            ],
            [
                'category_id' => 5,
                'title' => 'Python for Data Analysis',
                'slug' => 'python-for-data-analysis',
                'author' => 'Wes McKinney',
                'price' => 550000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 2500,
                'cover' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=500',
                'description' => 'Memproses data besar menggunakan Python.',
            ],
            [
                'category_id' => 5,
                'title' => 'Artificial Intelligence: A Modern Approach',
                'slug' => 'ai-a-modern-approach',
                'author' => 'Stuart Russell',
                'price' => 1100000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 4,
                'sold_count' => 350,
                'cover' => 'https://images.unsplash.com/photo-1620712943543-bcc4638ef808?q=80&w=500',
                'description' => 'Kurikulum standar AI di seluruh dunia.',
            ],
            [
                'category_id' => 5,
                'title' => 'Generative AI',
                'slug' => 'generative-ai',
                'author' => 'David Foster',
                'price' => 620000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 11,
                'sold_count' => 600,
                'cover' => 'https://images.unsplash.com/photo-1684369175833-31628328df8c?q=80&w=500',
                'description' => 'Memahami model GPT, BERT, dan Diffusion.',
            ],

            // ==========================================
            // 6. PSIKOLOGI
            // ==========================================
            [
                'category_id' => 6,
                'title' => 'Atomic Habits',
                'slug' => 'atomic-habits',
                'author' => 'James Clear',
                'price' => 165000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 50,
                'sold_count' => 15000,
                'cover' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=500',
                'description' => 'Perubahan kecil yang memberikan hasil luar biasa.',
            ],
            [
                'category_id' => 6,
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'author' => 'Daniel Kahneman',
                'price' => 195000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 20,
                'sold_count' => 8900,
                'cover' => 'https://images.unsplash.com/photo-1544716278-e513176fa20e?q=80&w=500',
                'description' => 'Bagaimana pikiran kita bekerja di bawah sadar.',
            ],
            [
                'category_id' => 6,
                'title' => 'Mans Search for Meaning',
                'slug' => 'mans-search-for-meaning',
                'author' => 'Viktor Frankl',
                'price' => 120000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 4500,
                'cover' => 'https://images.unsplash.com/photo-1516414447565-b14be0adf13e?q=80&w=500',
                'description' => 'Menemukan makna hidup di tengah penderitaan.',
            ],
            [
                'category_id' => 6,
                'title' => 'The Psychology of Money',
                'slug' => 'the-psychology-of-money',
                'author' => 'Morgan Housel',
                'price' => 150000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 30,
                'sold_count' => 12000,
                'cover' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=500',
                'description' => 'Hubungan psikologis antara manusia dan uang.',
            ],
            [
                'category_id' => 6,
                'title' => 'The Power of Habit',
                'slug' => 'the-power-of-habit',
                'author' => 'Charles Duhigg',
                'price' => 140000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 12,
                'sold_count' => 7600,
                'cover' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=500',
                'description' => 'Mengapa kita melakukan apa yang kita lakukan.',
            ],

            // ==========================================
            // 7. PENDIDIKAN
            // ==========================================
            [
                'category_id' => 7,
                'title' => 'Metode Mengajar Modern',
                'slug' => 'metode-mengajar-modern',
                'author' => 'Ki Hajar Dewantara',
                'price' => 90000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 100,
                'sold_count' => 500,
                'cover' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=500',
                'description' => 'Filsafat dan metode pengajaran dasar.',
            ],
            [
                'category_id' => 7,
                'title' => 'Pedagogy of the Oppressed',
                'slug' => 'pedagogy-of-the-oppressed',
                'author' => 'Paulo Freire',
                'price' => 110000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 25,
                'sold_count' => 3000,
                'cover' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=500',
                'description' => 'Teori pendidikan kritis untuk perubahan sosial.',
            ],
            [
                'category_id' => 7,
                'title' => 'The Learning Brain',
                'slug' => 'the-learning-brain',
                'author' => 'Sarah-Jayne Blakemore',
                'price' => 250000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 800,
                'cover' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=500',
                'description' => 'Bagaimana otak belajar di usia sekolah.',
            ],
            [
                'category_id' => 7,
                'title' => 'How to Read a Book',
                'slug' => 'how-to-read-a-book',
                'author' => 'Mortimer J. Adler',
                'price' => 135000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 20,
                'sold_count' => 4000,
                'cover' => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=500',
                'description' => 'Panduan klasik untuk membaca cerdas.',
            ],
            [
                'category_id' => 7,
                'title' => 'Digital Education',
                'slug' => 'digital-education',
                'author' => 'Neil Selwyn',
                'price' => 300000,
                'discount_percentage' => 20,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 450,
                'cover' => 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?q=80&w=500',
                'description' => 'Masa depan teknologi dalam pendidikan.',
            ],

            // ==========================================
            // 8. HUKUM & POLITIK
            // ==========================================
            [
                'category_id' => 8,
                'title' => 'The Republic',
                'slug' => 'the-republic',
                'author' => 'Plato',
                'price' => 120000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 15,
                'sold_count' => 6000,
                'cover' => 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?q=80&w=500',
                'description' => 'Filsafat tentang keadilan dan negara ideal.',
            ],
            [
                'category_id' => 8,
                'title' => 'Hukum Tata Negara Indonesia',
                'slug' => 'hukum-tata-negara',
                'author' => 'Jimly Asshiddiqie',
                'price' => 280000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 20,
                'sold_count' => 1200,
                'cover' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=500',
                'description' => 'Pemahaman komprehensif konstitusi kita.',
            ],
            [
                'category_id' => 8,
                'title' => 'The Social Contract',
                'slug' => 'the-social-contract',
                'author' => 'Jean-Jacques Rousseau',
                'price' => 95000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 2500,
                'cover' => 'https://images.unsplash.com/photo-1521791136064-7986c2923216?q=80&w=500',
                'description' => 'Asal mula hukum dan hak asasi manusia.',
            ],
            [
                'category_id' => 8,
                'title' => 'The Prince',
                'slug' => 'the-prince',
                'author' => 'Niccolo Machiavelli',
                'price' => 85000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 30,
                'sold_count' => 9000,
                'cover' => 'https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=500',
                'description' => 'Seni kekuasaan dan kepemimpinan politik.',
            ],
            [
                'category_id' => 8,
                'title' => 'International Law',
                'slug' => 'international-law',
                'author' => 'Malcolm Shaw',
                'price' => 1500000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 5,
                'sold_count' => 200,
                'cover' => 'https://images.unsplash.com/photo-1453941403708-341ff0b493e9?q=80&w=500',
                'description' => 'Panduan lengkap hukum internasional.',
            ],

            // ==========================================
            // 9. OLAHRAGA & KESEHATAN
            // ==========================================
            [
                'category_id' => 9,
                'title' => 'Strength Training Anatomy',
                'slug' => 'strength-training-anatomy',
                'author' => 'Frédéric Delavier',
                'price' => 320000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 1500,
                'cover' => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=500',
                'description' => 'Visualisasi otot saat latihan beban.',
            ],
            [
                'category_id' => 9,
                'title' => 'The Food Lab',
                'slug' => 'the-food-lab',
                'author' => 'Kenji López-Alt',
                'price' => 450000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 10,
                'sold_count' => 3200,
                'cover' => 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=500',
                'description' => 'Sains di balik masakan sehat di rumah.',
            ],
            [
                'category_id' => 9,
                'title' => 'Yoga Anatomy',
                'slug' => 'yoga-anatomy',
                'author' => 'Leslie Kaminoff',
                'price' => 280000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 20,
                'sold_count' => 900,
                'cover' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=500',
                'description' => 'Panduan anatomi untuk praktisi yoga.',
            ],
            [
                'category_id' => 9,
                'title' => 'Born to Run',
                'slug' => 'born-to-run',
                'author' => 'Christopher McDougall',
                'price' => 155000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 4300,
                'cover' => 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?q=80&w=500',
                'description' => 'Kisah suku pelari ultra-maraton hebat.',
            ],
            [
                'category_id' => 9,
                'title' => 'Bigger Leaner Stronger',
                'slug' => 'bigger-leaner-stronger',
                'author' => 'Michael Matthews',
                'price' => 210000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 25,
                'sold_count' => 5600,
                'cover' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=500',
                'description' => 'Panduan membangun tubuh tanpa steroid.',
            ],

            // ==========================================
            // 10. KULINER
            // ==========================================
            [
                'category_id' => 10,
                'title' => 'Salt, Fat, Acid, Heat',
                'slug' => 'salt-fat-acid-heat',
                'author' => 'Samin Nosrat',
                'price' => 390000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 8,
                'sold_count' => 6000,
                'cover' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=500',
                'description' => 'Empat elemen dasar masakan lezat.',
            ],
            [
                'category_id' => 10,
                'title' => 'Mastering Indonesian Cuisine',
                'slug' => 'mastering-indonesian-cuisine',
                'author' => 'William Wongso',
                'price' => 280000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 1200,
                'cover' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=500',
                'description' => 'Resep otentik nusantara dari sang maestro.',
            ],
            [
                'category_id' => 10,
                'title' => 'The Bread Baker Apprentice',
                'slug' => 'the-bread-baker-apprentice',
                'author' => 'Peter Reinhart',
                'price' => 420000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 5,
                'sold_count' => 850,
                'cover' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=500',
                'description' => 'Seni dan sains membuat roti tingkat dunia.',
            ],
            [
                'category_id' => 10,
                'title' => 'Plenty',
                'slug' => 'plenty-ottolenghi',
                'author' => 'Yotam Ottolenghi',
                'price' => 450000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 2100,
                'cover' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=500',
                'description' => 'Inovasi masakan sayuran modern.',
            ],
            [
                'category_id' => 10,
                'title' => 'Larousse Gastronomique',
                'slug' => 'larousse-gastronomique',
                'author' => 'Prosper Montagné',
                'price' => 1800000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 3,
                'sold_count' => 100,
                'cover' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=500',
                'description' => 'Ensiklopedia kuliner terbesar di dunia.',
            ],

            // ==========================================
            // 11. TRAVEL & ALAM
            // ==========================================
            [
                'category_id' => 11,
                'title' => 'Into the Wild',
                'slug' => 'into-the-wild',
                'author' => 'Jon Krakauer',
                'price' => 135000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 5200,
                'cover' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=500',
                'description' => 'Petualangan ekstrem mencari jati diri di alam.',
            ],
            [
                'category_id' => 11,
                'title' => 'The Alchemist',
                'slug' => 'the-alchemist',
                'author' => 'Paulo Coelho',
                'price' => 95000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 40,
                'sold_count' => 25000,
                'cover' => 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=500',
                'description' => 'Perjalanan mengejar legenda pribadi.',
            ],
            [
                'category_id' => 11,
                'title' => 'National Geographic Guide',
                'slug' => 'national-geographic-guide',
                'author' => 'National Geographic',
                'price' => 350000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 3000,
                'cover' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=500',
                'description' => 'Panduan visual taman nasional dunia.',
            ],
            [
                'category_id' => 11,
                'title' => 'Wild',
                'slug' => 'wild-cheryl',
                'author' => 'Cheryl Strayed',
                'price' => 165000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 4100,
                'cover' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=500',
                'description' => 'Perjalanan mendaki sendirian di PCT.',
            ],
            [
                'category_id' => 11,
                'title' => 'Lonely Planet World Guide',
                'slug' => 'lonely-planet-world',
                'author' => 'Lonely Planet',
                'price' => 600000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 8,
                'sold_count' => 1200,
                'cover' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=500',
                'description' => 'Rujukan terlengkap perjalanan global.',
            ],

            // ==========================================
            // 12. FOTOGRAFI
            // ==========================================
            [
                'category_id' => 12,
                'title' => 'Digital Photography',
                'slug' => 'digital-photography',
                'author' => 'Scott Kelby',
                'price' => 240000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 20,
                'sold_count' => 3400,
                'cover' => 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=500',
                'description' => 'Tips praktis menghasilkan foto profesional.',
            ],
            [
                'category_id' => 12,
                'title' => 'The Photographers Eye',
                'slug' => 'the-photographers-eye',
                'author' => 'Michael Freeman',
                'price' => 310000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 1800,
                'cover' => 'https://images.unsplash.com/photo-1493863641943-9b68992a8d07?q=80&w=500',
                'description' => 'Komposisi dan desain dalam fotografi.',
            ],
            [
                'category_id' => 12,
                'title' => 'Light Science and Magic',
                'slug' => 'light-science-and-magic',
                'author' => 'Fil Hunter',
                'price' => 580000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 5,
                'sold_count' => 600,
                'cover' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=500',
                'description' => 'Memahami teori pencahayaan yang kompleks.',
            ],
            [
                'category_id' => 12,
                'title' => 'Humans of New York',
                'slug' => 'hony-book',
                'author' => 'Brandon Stanton',
                'price' => 380000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 9000,
                'cover' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=500',
                'description' => 'Seni street photography dan cerita manusia.',
            ],
            [
                'category_id' => 12,
                'title' => 'Street Photography Now',
                'slug' => 'street-photography-now',
                'author' => 'Sophie Howarth',
                'price' => 290000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 10,
                'sold_count' => 1100,
                'cover' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=500',
                'description' => 'Eksplorasi fotografi jalanan kontemporer.',
            ],

            // ==========================================
            // 13. MUSIK
            // ==========================================
            [
                'category_id' => 13,
                'title' => 'Music Theory Dasar',
                'slug' => 'music-theory-dasar',
                'author' => 'L. Vanthy',
                'price' => 195000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 25,
                'sold_count' => 2300,
                'cover' => 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=500',
                'description' => 'Memahami notasi dan harmoni dasar.',
            ],
            [
                'category_id' => 13,
                'title' => 'How Music Works',
                'slug' => 'how-music-works',
                'author' => 'David Byrne',
                'price' => 265000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 1500,
                'cover' => 'https://images.unsplash.com/photo-1514320299584-4bd0075b7971?q=80&w=500',
                'description' => 'Sains, seni, dan sejarah musik dunia.',
            ],
            [
                'category_id' => 13,
                'title' => 'Piano for Dummies',
                'slug' => 'piano-for-dummies',
                'author' => 'Hal Leonard',
                'price' => 140000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 30,
                'sold_count' => 4500,
                'cover' => 'https://images.unsplash.com/photo-1520529612224-d2c6c7482869?q=80&w=500',
                'description' => 'Belajar piano mandiri untuk pemula.',
            ],
            [
                'category_id' => 13,
                'title' => 'The Beatles Biography',
                'slug' => 'the-beatles-bio',
                'author' => 'Mark Lewisohn',
                'price' => 420000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 8,
                'sold_count' => 800,
                'cover' => 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=500',
                'description' => 'Sejarah band paling berpengaruh di dunia.',
            ],
            [
                'category_id' => 13,
                'title' => 'Guitar Method Complete',
                'slug' => 'guitar-method-complete',
                'author' => 'Will Schmid',
                'price' => 180000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 40,
                'sold_count' => 6700,
                'cover' => 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?q=80&w=500',
                'description' => 'Metode lengkap belajar gitar akustik.',
            ],

            // ==========================================
            // 14. SEJARAH
            // ==========================================
            [
                'category_id' => 14,
                'title' => 'The Silk Roads',
                'slug' => 'the-silk-roads',
                'author' => 'Peter Frankopan',
                'price' => 245000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 3400,
                'cover' => 'https://images.unsplash.com/photo-1461360228754-6e81c478c882?q=80&w=500',
                'description' => 'Sejarah dunia dari perspektif Jalur Sutra.',
            ],
            [
                'category_id' => 14,
                'title' => 'Guns, Germs, and Steel',
                'slug' => 'guns-germs-and-steel',
                'author' => 'Jared Diamond',
                'price' => 195000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 20,
                'sold_count' => 7800,
                'cover' => 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?q=80&w=500',
                'description' => 'Nasib masyarakat manusia secara global.',
            ],
            [
                'category_id' => 14,
                'title' => 'Sejarah Indonesia Modern',
                'slug' => 'sejarah-indonesia-modern',
                'author' => 'M.C. Ricklefs',
                'price' => 320000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 12,
                'sold_count' => 2100,
                'cover' => 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?q=80&w=500',
                'description' => 'Catatan lengkap sejarah Nusantara modern.',
            ],
            [
                'category_id' => 14,
                'title' => 'The Crusades',
                'slug' => 'the-crusades',
                'author' => 'Thomas Asbridge',
                'price' => 280000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 10,
                'sold_count' => 1100,
                'cover' => 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?q=80&w=500',
                'description' => 'Sejarah definitif Perang Salib.',
            ],
            [
                'category_id' => 14,
                'title' => 'SPQR: A History of Rome',
                'slug' => 'spqr-rome',
                'author' => 'Mary Beard',
                'price' => 275000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 18,
                'sold_count' => 4500,
                'cover' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=500',
                'description' => 'Bangkit dan runtuhnya kekaisaran Romawi.',
            ],

            // ==========================================
            // 15. KEUANGAN PERSONAL
            // ==========================================
            [
                'category_id' => 15,
                'title' => 'The Psychology of Money',
                'slug' => 'psychology-of-money-alt',
                'author' => 'Morgan Housel',
                'price' => 145000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 40,
                'sold_count' => 15000,
                'cover' => 'https://images.unsplash.com/photo-1579621909532-935716ad2f24?q=80&w=500',
                'description' => 'Hubungan emosional kita dengan uang.',
            ],
            [
                'category_id' => 15,
                'title' => 'The Total Money Makeover',
                'slug' => 'total-money-makeover',
                'author' => 'Dave Ramsey',
                'price' => 185000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 25,
                'sold_count' => 8900,
                'cover' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=500',
                'description' => 'Langkah praktis bebas hutang selamanya.',
            ],
            [
                'category_id' => 15,
                'title' => 'The Richest Man in Babylon',
                'slug' => 'richest-man-babylon',
                'author' => 'George S. Clason',
                'price' => 85000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 50,
                'sold_count' => 20000,
                'cover' => 'https://images.unsplash.com/photo-1565514020179-026b92b84bb6?q=80&w=500',
                'description' => 'Rahasia kuno untuk menumpuk kekayaan.',
            ],
            [
                'category_id' => 15,
                'title' => 'I Will Teach You to Be Rich',
                'slug' => 'teach-you-to-be-rich',
                'author' => 'Ramit Sethi',
                'price' => 210000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 4600,
                'cover' => 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=500',
                'description' => 'Sistem otomatisasi keuangan pribadi.',
            ],
            [
                'category_id' => 15,
                'title' => 'Financial Freedom',
                'slug' => 'financial-freedom',
                'author' => 'Grant Sabatier',
                'price' => 195000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 20,
                'sold_count' => 3100,
                'cover' => 'https://images.unsplash.com/photo-1454165833767-02a698d48722?q=80&w=500',
                'description' => 'Strategi pensiun dini dengan investasi tepat.',
            ],

            // ==========================================
            // 16. LIFESTYLE
            // ==========================================
            [
                'category_id' => 16,
                'title' => 'Minimalism Life',
                'slug' => 'minimalism-life',
                'author' => 'Joshua Fields Millburn',
                'price' => 130000,
                'discount_percentage' => 10,
                'is_on_sale' => true,
                'stock' => 20,
                'sold_count' => 4500,
                'cover' => 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?q=80&w=500',
                'description' => 'Hidup lebih bermakna dengan barang sedikit.',
            ],
            [
                'category_id' => 16,
                'title' => 'Ikigai: Rahasia Panjang Umur',
                'slug' => 'ikigai-lifestyle',
                'author' => 'Héctor García',
                'price' => 110000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 35,
                'sold_count' => 18000,
                'cover' => 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=500',
                'description' => 'Konsep Jepang untuk hidup yang seimbang.',
            ],
            [
                'category_id' => 16,
                'title' => 'The Book of Hygge',
                'slug' => 'hygge-comfort',
                'author' => 'Meik Wiking',
                'price' => 155000,
                'discount_percentage' => 5,
                'is_on_sale' => true,
                'stock' => 15,
                'sold_count' => 6700,
                'cover' => 'https://images.unsplash.com/photo-1512310604669-443f06c350ad?q=80&w=500',
                'description' => 'Kenyamanan dan kebahagiaan ala Denmark.',
            ],
            [
                'category_id' => 16,
                'title' => 'The Subtle Art of Not Giving',
                'slug' => 'subtle-art-manson',
                'author' => 'Mark Manson',
                'price' => 160000,
                'discount_percentage' => 15,
                'is_on_sale' => true,
                'stock' => 40,
                'sold_count' => 25000,
                'cover' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=500',
                'description' => 'Seni bersikap tidak peduli pada hal sepele.',
            ],
            [
                'category_id' => 16,
                'title' => 'Digital Minimalism',
                'slug' => 'digital-minimalism-cal',
                'author' => 'Cal Newport',
                'price' => 175000,
                'discount_percentage' => 0,
                'is_on_sale' => false,
                'stock' => 12,
                'sold_count' => 5400,
                'cover' => 'https://images.unsplash.com/photo-1521931961826-fe48677230a5?q=80&w=500',
                'description' => 'Tetap fokus di dunia digital yang bising.',
            ],
        ];

        // Mass insert dengan timestamp otomatis
        $data = array_map(function ($book) {
            $book['created_at'] = now();
            $book['updated_at'] = now();
            return $book;
        }, $books);

        DB::table('books')->insert($data);
    }
}